### ISSUE TITLE
Make it eager

### ISSUE THREAD

**Issue by adi518** [warrenday/graphql-network-inspector#14]
The extension doesn't log network requests if the tab is not focused. It means you have to refresh to get the log. Making it eager should fix it.

**Comment by warrenday** [comment]
Requests are logged if the tab has been focused at least once since devtools was opened. Prior to this, the app has not booted, and therefore no script execution can happen.

A fix for this would be to detect first load and call `chrome.devtools.network.getHAR()` to return historic network requests and load them into the app.

Are you aware of another method? I am not sure what you mean by "make it eager"?

**Comment by adi518** [comment]
Eager means it should log as soon as possible, regardless of user interaction. Since you said the extension doesn't execute in the background, the other way around sounds like the solution, getting historic network requests and provide the log for it. Sounds easy to implement too.

**Comment by warrenday** [comment]
PR has been merged for this via the method described above.
https://github.com/warrenday/graphql-network-inspector/pull/17

I'll release this to chrome store soon.

**Comment by adi518** [comment]
Give this man a huge round of applause. Awesome work @warrenday.
