### ISSUE TITLE
Just doesnt work in chrome.

### ISSUE THREAD

**Issue by CGottschallJ** [warrenday/graphql-network-inspector#158]
**Describe the bug**
Unfortunately, it just doesn't work in in chrome.  It crashes almost every time that I open it, I have to close dev tools and re-open it on every refresh to make it work.  A lot of times when I close dev tools and re-open it, the tab does not even exist anymore.  Then I have to try and open a new browser window to see if it appears there. Half of the time it doesn't. Half of the time when it does appear to be up and running, none of the requests are even displayed.

**To Reproduce**

1. Go to 'dev tools'
2. Click on ' the double arrows for more dev tools panels'
3. Does not exist in list.

Another is...
1. Go to 'dev tools'
2. click on graphql tab
3. no queries get listed when they are called.
4. dev tools crash

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/ebea4260-132c-4f24-beff-013e698b8b50)

![image](https://github.com/user-attachments/assets/279ed7ae-80e7-4a3e-901d-10f8056a5f49)

**Desktop (please complete the following information):**

- OS: MacOS 15.1
- Version 131.0.6778.86 (Official Build)

**Additional context**
Has been doing this since I installed the first time months ago.

**Comment by warrenday** [comment]
Might be worth right clicking in the inspector window and clicking inspect. There may be some useful information in the console there.

**Comment by CGottschallJ** [comment]
Hey  Warren, Could you elaborate please? Im not exactly sure I understand

**Comment by warrenday** [comment]
You can inspect element on the extension window itself, this will show the console which may show some local errors.

Since the app is not working for you at all, their seems to be something specific.

Maybe the way your graph is configured, maybe a conflict with another extension, or maybe something with a chrome setting.

I can't recreate the error you're seeing since the app is working fine for me. But if I spot something specific I may be able to replicate on my end and then fix.

**Comment by warrenday** [comment]
Closing as inactive. Provide a reproducible example and I can look into it further.
