### ISSUE TITLE
GET requests are not detected

### ISSUE THREAD

**Issue by adrian-skybaker** [warrenday/graphql-network-inspector#70]
See the GET section of https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md for the convention of the serialization format when GET is used instead of POST.

**Comment by warrenday** [comment]
Currently we are only parsing POST, however it should be fairly straightforward to also listen for GET requests. Thanks for raising. 🙌

**Comment by Odonno** [comment]
I made a PR that detect GET/Persisted Query requests #81. @adrian-skybaker Because each framework has its own implementation, what I have done may not work for you. If that's the case, are you able to provide an example of a GET request (url + headers) that should work? So that I can tweak the code to make it work.
