### ISSUE TITLE
Vite ecosystem migration

### ISSUE THREAD

**Issue by Odonno** [warrenday/graphql-network-inspector#89]
**Is your feature request related to a problem? Please describe.**

Take advantage of the Vite ecosystem (Vite, Vitest, etc...) by migrating from cra to Vite. This will improve compile time and should also reduce bundle size.

@warrenday I don't know if you use special features of CRA. If you use any, that could be interested to list them here.

**Comment by warrenday** [comment]
CRA was used purely because it was the most popular choice at the time. However, we are using "writeToDisk" in craco.config which allows us to develop the app as an unpacked extension.

1. Start the app with `yarn start`
2. Load the "dist" folder as an "unpacked" extension on chrome
3. Now when you make changes you can see them instantly in the real chrome extension.

This is sometimes referred over working with the mocked data, if testing the chrome api's.

Don't mind switching to vite however the app is pretty small, so build times are still fast regardless.

**Comment by warrenday** [comment]
Closing as no current plans to move build system. We could move to this in future. But it's low priority.
